#!/bin/sh
set -eu

##DEBHELPER##

if [ ! -f "${DPKG_ROOT:-}/etc/skel/.bashrc" ]; then
    touch "${DPKG_ROOT:-}/etc/skel/.bashrc"
fi
"${DPKG_ROOT:-}/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/edit-bashrc.sh" \
    "${DPKG_ROOT:-}/etc/skel/.bashrc"

# loop through all existing user bashrc files, and if they currently
# use qyanu-bash-tweaks then update their respective marked section.
while read homedir_value;
do
    homedir="${DPKG_ROOT:-}${homedir_value}"
    if [ ! -d "${homedir}" ]; then
        continue
    fi
    filetoedit="${homedir}/.bashrc"
    if [ ! -f "${filetoedit}" ]; then
        continue
    fi
    if ! grep -qPe "## BEGIN: qyanu-bash-tweaks" "${filetoedit}"; then
        continue
    fi
    "${DPKG_ROOT:-}/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/edit-bashrc.sh" \
        "${filetoedit}"
done \
    < <(getent passwd | cut -d ":" -f 6 | sort -u)
